// ESLint flat configuration shared by every JavaScript/TypeScript workspace.
//
// Deliberately no type-aware linting: `parserOptions.project` requires a TypeScript project per linted
// file, and type checking is already enforced separately and strictly by `tsc --build` in
// scripts/typecheck.mjs. Keeping ESLint type-unaware means the lint gate stays fast and independent of
// which dependencies happen to be installed locally.
import js from "@eslint/js";
import nextPlugin from "@next/eslint-plugin-next";
import eslintConfigPrettier from "eslint-config-prettier";
import globals from "globals";
import typescriptEslint from "typescript-eslint";

// Only tracked repository sources are linted. Vendored and generated trees are ignored explicitly:
// ESLint does not ignore dot-directories by default, and the Python virtual environment ships its own
// JavaScript assets (for example the coverage HTML report) that must never be linted.
const sourceGlobs = [
  "*.{js,mjs,cjs,ts,mts,cts,tsx,jsx}",
  "apps/**/*.{js,mjs,cjs,ts,mts,cts,tsx,jsx}",
  "packages/**/*.{js,mjs,cjs,ts,mts,cts,tsx,jsx}",
  "services/**/*.{js,mjs,cjs,ts,mts,cts,tsx,jsx}",
  "scripts/**/*.{js,mjs,cjs,ts,mts,cts,tsx,jsx}",
  "tests/**/*.{js,mjs,cjs,ts,mts,cts,tsx,jsx}",
  ".github/**/*.{js,mjs,cjs}",
];

export default [
  // A global-ignore object must contain only `ignores`, which is why it is kept separate from the
  // `linterOptions` object below. Vendored and generated trees are listed explicitly because ESLint
  // does not ignore dot-directories by default.
  {
    ignores: [
      "**/node_modules/**",
      ".venv/**",
      "**/.venv/**",
      "**/.git/**",
      "**/.next/**",
      "**/dist/**",
      "**/build/**",
      "**/out/**",
      "**/coverage/**",
      "**/htmlcov/**",
      "**/.pytest_cache/**",
      "**/.mypy_cache/**",
      "**/.ruff_cache/**",
      "infra/**",
      "observability/grafana/dashboards/**",
      // Generated by Next.js on every build. It is committed so a fresh clone type-checks without one,
      // but it must not be linted: the file is machine-written and its triple-slash references are
      // Next.js's own, not hand-written imports.
      "apps/demo-app/frontend/next-env.d.ts",
    ],
  },
  {
    linterOptions: {
      reportUnusedDisableDirectives: "error",
    },
  },
  js.configs.recommended,
  ...typescriptEslint.configs.recommended,
  {
    files: sourceGlobs,
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      globals: {
        ...globals.node,
      },
    },
    rules: {
      eqeqeq: ["error", "always", { null: "ignore" }],
      "no-var": "error",
      "prefer-const": "error",
      "no-console": ["warn", { allow: ["error", "warn", "info"] }],
      "no-param-reassign": "error",
      "no-else-return": "error",
      "object-shorthand": "error",
      "sort-imports": ["error", { ignoreDeclarationSort: true }],
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  {
    // The demo frontend executes both in the browser (React client components) and in Next.js's Node.js
    // server runtime (server components, config files), so both global sets apply. Listing them keeps
    // `no-undef` meaningful instead of disabling it for the workspace.
    files: ["apps/**/*.{js,mjs,cjs,ts,mts,cts,tsx,jsx}"],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
  },
  {
    // Next.js specific rules (no `<img>` in place of `next/image`, no sync scripts, no direct
    // `document`-based redirects, and so on). Scoped to the frontend workspace so the rules only apply
    // where a Next.js application actually lives; `next build` warns when the plugin is missing.
    files: ["apps/demo-app/frontend/**/*.{js,mjs,cjs,ts,mts,cts,tsx,jsx}"],
    plugins: { "@next/next": nextPlugin },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs["core-web-vitals"].rules,
      // The workspace is App Router only, so the plugin's Pages Router rule has nothing to inspect and
      // would otherwise print a "pages directory cannot be found" notice on every lint run.
      "@next/next/no-html-link-for-pages": "off",
    },
  },
  {
    // Test files may use non-null assertions and print diagnostics.
    files: ["**/*.test.{ts,tsx,js,mjs}", "**/tests/**/*.{ts,tsx,js,mjs}"],
    rules: {
      "no-console": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
    },
  },
  // Must stay last: disables rules that conflict with Prettier formatting.
  eslintConfigPrettier,
];
