# Placeholder lockfile - generated by running: terraform init && terraform providers lock -platform=windows_amd64
# This file pins provider versions for reproducible builds (Task 4.3).
# Replace with a real lockfile when Terraform is available in the environment.
provider "registry.terraform.io/hashicorp/aws" {
  version     = "5.50.0"
  constraints = ">= 5.0"
}

provider "registry.terraform.io/hashicorp/random" {
  version     = "3.6.1"
  constraints = ">= 3.0"
}
